### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by alexstine** [Zhouzi/hide-files-from-bitbucket-pr#4]
Hello,

I am having trouble with documentation you provided. Can you give me some instruction on how to exclude JS files? I have tried *.js, not sure what else to try.

Thanks.

**Comment by zhouzi** [comment]
Hey! Sorry for the delay. I haven't used this extension for a while and Bitbucket went through a few redesigns so I wouldn't be surprised if it was not working anymore. I'll have a look and see if it can be updated easily 👌 I will keep you posted through this issue.

**Comment by zhouzi** [comment]
So I just gave it a try and it seems that it's all working as expected. If you wish to hide all .js files, you can use the pattern `**/*.js`

Feel free to reopen this issue if you're still having trouble with anything 😉

**Comment by alexstine** [comment]
Hello @Zhouzi ,

I think for the future, you should work on adding a feature in reverse where you input which files you want to show by default. E.g. I mainly develop with PHP files and I don't need hundreds of .scss .css .css.map files loading. Just a way to make things a little quicker.

This is an awesome extension and something Bitbucket should have integrated in to their current diff system instead of this new annoying complicated one.

Thanks.

**Comment by zhouzi** [comment]
Thanks for the kind words 😊 You should be able to hide all files except `.php`s with the following pattern: `!**/*.php`

I agree that it may not be super user-friendly when what you want is to only show certain files. Adding an option as you suggested would definitely be a cool improvement 👍
